# Generated by Django 3.0.1 on 2019-12-26 23:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='created_by',
            field=models.CharField(default=' ', max_length=100),
        ),
    ]
